[workspace]
members = [
    "share_type_public",
    "rust/common",
    "rust/dominoes",
    "rust/landlord",
    "rust/shenyang_mahjong",
    "rust/poker_core",
    "rust/holdem",
    "rust/tractor",
    "rust/upgrade_common",
    "rust/upgrade",
    "rust/p2p",
    "rust/android_server",
]
default-members = [
    "share_type_public",
    "rust/common",
    "rust/dominoes",
    "rust/landlord",
    "rust/shenyang_mahjong",
    "rust/poker_core",
    "rust/holdem",
    "rust/tractor",
    "rust/upgrade_common",
    "rust/upgrade",
    "rust/p2p",
]
resolver = "3"
