[package]
name = "tractor"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
default = []
official = [
    "dep:data",
    "data/cache-redis",
    "dep:runtime_common",
    "dep:tracing",
]

[dependencies]
anyhow = "1"
data = { path = "../../../data", optional = true }
rand = "0.9"
upgrade_common = { path = "../upgrade_common" }
runtime_common = { path = "../../../runtime_common", optional = true }
serde = "1"
serde_json = "1"
share_type_public = { path = "../../share_type_public" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = { version = "0.1", optional = true }
ws_common = { path = "../common" }

[dev-dependencies]
futures-util = "0.3"
tokio-tungstenite = "0.29"
