[package]
name = "dominoes"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
default = []
official = [
    "dep:data",
    "data/cache-redis",
    "dep:runtime_common",
    "dep:tracing",
]

[dependencies]
anyhow = "1"
data = { path = "../../../data", optional = true }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
share_type_public = { path = "../../share_type_public" }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
ws_common = { path = "../common" }
runtime_common = { path = "../../../runtime_common", optional = true }
tracing = { version = "0.1", optional = true }

[dev-dependencies]
futures-util = "0.3"
tokio-tungstenite = "0.29"
